version: '3'
services:
 odoo:
   image: odoo:12.0
   depends_on:
     - db
   ports:
     - 8069:8069
   volumes:     
     - odoo-web-data:/var/lib/odoo
     - ./odoo:/usr/lib/phyton3/dist-packages/odoo
     - ./config:/etc/odoo
     - ./extra-addons:/mnt/extra-addons
     - ./debug:/usr/lib/phyton3.5/debug
   command:
     - --dev=all
 db:
   image: postgres:10.0
   environment:
     - POSTGRES_PASSWORD=odoo
     - POSTGRES_USER=odoo
     - POSTGRES_DB=postgres
     - PGDATA=/var/lib/postgresql/data/pgdata
   volumes:
     - odoo-db-data:/var/lib/postgresql/data/pgdata
 pgadmin:
   image: thajeztah/pgadmin4
   ports:
     - 5050:5050
   links:
     - db
volumes:
 odoo-web-data:
 odoo-db-data:
